<?php

$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
?>

<fieldset>
    <legend>Consultar Curso</legend>
    <div class="row">
        <div class="form-group col-md-6 col-xs-6">
            <?php echo $this->formLabel($form->get('nmCurso')); ?>
            <?php echo $this->formInput($form->get('nmCurso')); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get('sgCurso')); ?>
            <?php echo $this->formInput($form->get('sgCurso')); ?>
        </div>
    </div>

    <div class="pull-left">
        <button type="button" name="cancelar" class="btn btn-default" id="cadastrar" value="Cadastrar"> Cadastrar </button>
        <button type="button" name="button" class="btn btn-primary" id="consultar" value="Consultar"> Consultar</button>
    </div>

    <div class="row" style="display: none;" id="divTabelaUsuario">
        <div class="form-group col-ms-12 col-xs-12">
            <table class="table display" id="DadosTabela" style="word-break:break-all">

                <tbody id="tbodyTable">

                </tbody>
            </table>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</fieldset>

<script>

    $(document).ready(function () {
        //'use strict';
        cadastrar();
        consultar();
    });

    function cadastrar() {
        $('#cadastrar').on('click', function () {
            window.location.assign('/application/index/cadastrar');
        });
    }

    function consultar() {
        $('#consultar').click(function () {
            $.ajax({
                datatype: 'JSON',
                url: "listar-curso",
                type: "GET",
                success: function (data) {
                    var retorno = JSON.parse(data);
                    console.log(retorno.dados);
                    var dataSet = [];
                    $.each(retorno.dados, function (index, data) {
                        dataSet.push([data.noCurso, data.sgCurso, data.chCurso])
                    });
                    $('#DadosTabela').DataTable({
                        data: dataSet,
                        columns: [
                            {title: 'Nome'},
                            {title: 'Sigla'},
                            {title: "CargaHoraria"}
                        ]
                    });
                }
            });
        });
    }


</script>