<?php

$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
?>

<fieldset>
    <legend>Consultar Curso</legend>
    <div class="row">
        <div class="form-group col-md-6 col-xs-6">
            <?php echo $this->formLabel($form->get('nmCurso')); ?>
            <?php echo $this->formInput($form->get('nmCurso')); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get('sgCurso')); ?>
            <?php echo $this->formInput($form->get('sgCurso')); ?>
        </div>
    </div>

    <div class="pull-left">
        <button type="button" name="cancelar" class="btn btn-default" id="cadastrar" value="Cadastrar"> Cadastrar </button>
        <button type="button" name="button" class="btn btn-primary" id="consultar" value="Consultar"> Consultar</button>
    </div>

    <div class="row" style="display: none;" id="divTabelaCurso">
        <div class="form-group col-ms-12 col-xs-12">
            <table class="table display" id="DadosTabela" style="word-break:break-all">
                <thead>
                    <tr>
                        <th style="width: 15%">Nome</th>
                        <th style="width: 25%">Sigla</th>
                        <th style="width: 20%">Carga Horaria</th>
                        <th style="width: 10%">Ação</th>
                    </tr>
                </thead>

                <tbody id="tbodyTable">

                </tbody>
            </table>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</fieldset>

<script>

    $(document).ready(function () {
        //'use strict';
        cadastrar();
        consultarCurso();
    });

    function cadastrar() {
        $('#cadastrar').on('click', function () {
            window.location.assign('/application/index/cadastrar');
        });
    }

    function consultarCurso() {
        $('#consultar').click(function () {

            $('#divTabelaCurso').show();
//            $('#DadosTabela').DataTable().destroy();
            $('#DadosTabela').DataTable({
                'searching': false,
                "pageLength": 10,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado para o filtro informado",
                    "sInfo": "Mostrando de START até END de TOTAL registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de MAX registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                },
                "ajax": {
                    url: "/application/index/consultar",
                    dataType: "JSON",
                    type: "POST",
                    data: {
                        "nome": $('#nmCurso').val(),
                        "sigla": $('#sgCurso').val(),
                        "cargahoraria": $('#chCurso').val()
                    },
                    dataSrc: ""
                },
                'columns': [
                    {"data": "nmCurso"},
                    {"data": "sgCurso"},
                    {"data": "chCurso"},
                    {
                        'class': 'text-center',
                        "data":
                            function (data) {
                                    return '<a href="/application/index/cadastrar?id=' + data.coUsuario + '" data-toggle="tooltip" title="Editar">' +
                                        '<i class="fa fa-pencil text-primary"></i>' +
                                        '</a>'
                            }

                    }
                ],
                "infoCallback": function (settings, start, end, max, total, pre) {
                    start = (total == 0) ? 0 : start;

                    if (start == 0) {
                        $('#btnExportaCSV').prop('disabled', true);
                    } else {
                        $('#btnExportaCSV').prop('disabled', false);
                    }

                    return "Mostrando registros de " + start + " a " + end + " de um total de " + total
                        + ((total !== max) ? " (filtrado de" + max + " total registros)" : "");
                }
            });
        });
    }

//            $.ajax({
//                datatype: 'JSON',
//                url: "listar-curso",
//                type: "GET",
//                success: function (data) {
//                    var retorno = JSON.parse(data);
//                    var dataSet = [];
//                    $.each(retorno.dados, function (index, data) {
//                        dataSet.push([data.noCurso, data.sgCurso, data.chCurso])
//                    });
//                    $('#DadosTabela').DataTable({
//                        data: dataSet,
//                        columns: [
//                            {title: 'Nome'},
//                            {title: 'Sigla'},
//                            {title: "CargaHoraria"}
//                        ]
//                    });
//                }
//            });
//        });

</script>